# configuration for https://travis-ci.org
language: python

# delegate tests to tox; build matrix contains one suite per testenv
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=lint
matrix:
  include:
    # python3.5 is not pre-installed on Travis,
    # https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-143758799
    - env: TOXENV=py35
      python: 3.5
    - env: BOULDER_INTEGRATION=1
      language: go
      go: 1.5.1
      services:
        - rabbitmq
      addons:
        mariadb: '10.0'
        apt:
          # keep in sync with bootstrap.sh and below
          packages:
            - ca-certificates
            - gcc
            - libssl-dev
            - libffi-dev
            - python
            - python-dev
            - python-virtualenv

install: tests/travis.sh install
script: tests/travis.sh script

# container-based architecture
sudo: false
addons:
  apt:
    # keep in sync with bootstrap.sh and above
    packages:
      - ca-certificates
      - gcc
      - libssl-dev
      - libffi-dev
      - python
      - python-dev
      - python-virtualenv

notifications:
  irc:
    channels:
      - "irc.freenode.org#simp_le"
    use_notice: true
    skip_join: true
